// web-display-react/src/App.js
import React, { useState, useEffect } from "react";
import UserPage from './UserPage'
import UserFormClass from "./UserFormClass";
import BuildGallery from "./BuildGallery";
import Navbar from "./Navbar";
import { BrowserRouter as Router, Switch, Route, Redirect } from "react-router-dom";
import Gallery from "./Gallery";
import Login from './Login'
import Welcome from './Welcome'

function App() {

  const [user, setUser] = useState({})
  const [loggedIn, setLoggedIn] = useState(false)

  useEffect( () => {
    if(localStorage.getItem('user')){
      setLoggedIn(true) 
      setUser(JSON.parse(localStorage.getItem('user')))
    }
  },[])

  return (
    <Router>
      <div className="App"  >
        <Navbar loggedIn={loggedIn} user={user} />
        <Switch>
          { loggedIn ?
              <Route path="/" exact component={() => <Welcome user={user} setLoggedIn={setLoggedIn} setUser={setUser} />} />
            :
              <Route path="/" exact
              render={() => (
                <UserFormClass setLoggedIn={setLoggedIn} setUser={setUser} loggedIn={loggedIn} />)}
              />
          }
          <Route path="/userpage" exact
            render={() => (
            <UserPage user={user} setUser={setUser} loggedIn={loggedIn} setLoggedIn={setLoggedIn} />)}
          />
          <Route path="/login" 
          render={() => (
            <Login setLoggedIn={setLoggedIn} setUser={setUser} loggedIn={loggedIn} />)}
          />
          <Route path="/buildgallery" component={() => <BuildGallery user={user} setUser={setUser} loggedIn={loggedIn} /> } />
          <Route path="/gallery" component={() => <Gallery user={user} loggedIn={loggedIn} /> } />
          <Redirect to="/" />
        </Switch>
      </div>
    </Router>
  );
}

export default App;

// web-display-vue/src/App.vue
<template>
  <div>
    <Navbar />
  </div>
</template>

<script>
import { mapState, mapMutations } from 'vuex'
import Navbar from './components/Navbar.vue'
import './css/main.css'

export default {
  name: 'App',
  components: {
    Navbar,
  },
  data() {
    return {
     
    }
  },
   mounted() {
      if( !this.loggedIn && localStorage.getItem('user')){
          this.setUser(JSON.parse(localStorage.getItem('user')))
          this.logIn()
      }else
      if( !this.loggedIn && sessionStorage.getItem('galleryimages') ){
          this.setGallery(JSON.parse(sessionStorage.getItem('galleryimages')))
      }
    },
  computed: {
      ...mapState(['user','loggedIn']),
  },
  methods: {
      ...mapMutations(['setUser','setGallery','logIn'])
  }
}
</script>

<style>

</style>
