// web-display-vue/src/components/Welcome.vue
<template>
  <div>
      <br />
      <h1 id="hh1">Välkommen {{$store.state.user.username}} </h1>
      <router-link to="/" tag="button" @click="() =>  {$store.commit('logOut');$router.push('/');}">Logga ut</router-link>
      </div>
</template>

<script>


export default {
    name: 'Welcome',
    components: {
        
        
    },

}
</script>

<style>
h1 {
    text-align: center;
}
#hh1 {
    text-align: center;
}
</style>

// web-display-react/src/components/Welcome.js
import React from 'react'


function Welcome(props){
    const logout = () => {
        localStorage.clear();
        props.setUser({});
        props.setLoggedIn(false)
      };

    return(
        <main>
            <h1 style={{textAlign: 'center'}}>Välkommen {props.user.username}</h1>
            <button style={{display: 'block',margin: 'auto'}} onClick={logout}>Logga ut</button>
        </main>
    )
}

export default Welcome
