// web-display-vue/src/components/Gallery.vue
<template>
  <br /><br /><br />
    <div id="lightbox" v-if="large_image" @click.stop="large_image = ''">
        <span class="lbnav" v-if="getImgIndex() > 0"  @click.stop="() => {loading = true;imgNav(-1)}">-></span>
        <div id="lbimgcontainer">
            <img class="lbimg" :src="large_image" @load="loading = false" />
            <span id="lbload" v-if="loading" >loading...</span>
            <span id="lbclose" @click="large_image = ''">X</span>
        </div>
        <span class="lbnav" v-if="getImgIndex() < user.galleryimages.length - 1" @click.stop="() => {loading = true;imgNav(1)}">-></span>
    </div>
    <div class="imagecontainer" v-if="user.galleryimages.length">
        <span class="prev_card" v-bind:key="img.id" v-for="img in user.galleryimages">
            <img class="prev_card_img" :src="img.previewURL" @click="large_image = img.largeImageURL" />
             <div class="prev_card_info">
                Sökord: {{img.query}}<br />
                Sparad: {{getSaveDate(img)}}
            </div>
        </span>
    </div>
    <div v-else>Ditt galleri är förvärvarande tomt, gå till 'Bygg galleri' för att lägga till bilder</div>
</template>

<script>
import { mapState, mapMutations } from 'vuex'

export default {

    name: 'Gallery',
    data() {
        return {
            gallery_images: [],
            large_image: "",
            loading: false,
        }
    },
    // mounted() {
    //   if( !this.loggedIn && localStorage.getItem('user')){
    //       this.setUser(JSON.parse(localStorage.getItem('user'))[0])
    //       this.logIn()
    //   }else
    //   if( !this.loggedIn && sessionStorage.getItem('galleryimages') ){
    //       this.setGallery(JSON.parse(sessionStorage.getItem('galleryimages')))
    //   }
    // },
    computed: {
        ...mapState(['user','loggedIn']),
       
    },
    methods: {
        test: () => console.log(this.loggedIn),
        ...mapMutations(['setGallery','setUser','logIn']),
        imgNav(move_index){
            const index = this.getImgIndex()
            this.large_image = this.user.galleryimages[index + move_index].largeImageURL
        },
        getImgIndex() {
            const index = this.user.galleryimages.findIndex(img => img.largeImageURL === this.large_image)
            console.log(index)
            return index
        },
        getSaveDate: img => {
            const date = new Date(img.time)
            const options = {  
                year: "numeric", month: "short",  
                day: "numeric", hour12: false, hour: "2-digit", minute: "2-digit"  
            };
            return date.toLocaleTimeString("en-us", options)
        }
    }

}
</script>

<style>
.prev_card {
  width: 170px;
  height: 180px;
  border-radius: 5px;
  background-color: rgba(207, 195, 248, 0.75);
  padding: 10px;
  box-shadow: 2px 2px 5px rgba(0, 0, 0, 1);
}

.prev_card_img {
  width: 150px;
  height: 100px;
  box-shadow: 0px 0px 3px rgba(0, 0, 0, 1);
}

</style>

// web-display-react/src/Gallery.js
import React, { useState, useEffect } from "react";
import { Link } from 'react-router-dom'
import imagesearch from './imagesearch'
import './css/SearchImages.css'

function Gallery(props){
    const [gallery_images,setGalleryImages] = useState([])
    const [large_image,setLargeImage] = useState("")
    const [image_index,setImageIndex] = useState(-1)
    const [loading,setLoading] = useState(false)

    useEffect( () => {
        if(sessionStorage.getItem('imagearray')){
        setGalleryImages(JSON.parse(sessionStorage.getItem('imagearray')))
        console.log(props.location.savedImages)}
        },[])

    const imageNav = (e,nav_index) => {
        e.stopPropagation()  
        const index = gallery_images.findIndex(img => img.largeImageURL === large_image) + nav_index
        console.log(index+" "+gallery_images.length)
        if(index > -1 && index < gallery_images.length){
            setLargeImage(
            gallery_images[(gallery_images.findIndex(img => img.largeImageURL === large_image)) + nav_index]
            .largeImageURL)
        }
    }

    return(
        <div className='imagecontainer'>
            {
                
                large_image ?
                <div id="lightbox" onClick={(e) => setLargeImage("") }>
                    {
                        gallery_images.findIndex(img => img.largeImageURL === large_image) !== 0 ?  
                            <span className="lbnav" onClick={(e) => {
                                setLoading(true)
                                imageNav(e,-1)}}
                                 >{"<-"}</span>
                        : null
                    }
                    <div id="lbimgcontainer">
                        <img src={large_image} className="lbimg" onLoad={() => setLoading(false)} onClick={(e) => {
                            e.stopPropagation() }}/>
                        {loading ? <span id="lbload" >loading...</span> : null}
                        <span id="lbclose" onClick={(e) => setLargeImage("")
                    } >
                            X</span>
                    </div>
                    {
                        gallery_images.findIndex(img => img.largeImageURL === large_image) + 1 < gallery_images.length ?  
                            <span className="lbnav" onClick={(e) => {
                                setLoading(true)
                                imageNav(e,1)}}>{"->"}</span>
                        : null
                    }
                </div>
                : null
                }
            { gallery_images.length ? gallery_images.map(image => {
                return (
                    <span>
                    <img src={image.previewURL} id={image.id} onClick={() => {
                        setLoading(true)
                        setLargeImage(image.largeImageURL)
                        }} />
                    </span >
                    )
                })
                : <div>Ditt galleri är förvärvarande tomt, gå till 'Bygg galleri' för att lägga till bilder</div>
            }
        </div>
    )
}
export default Gallery;
