// web-display-vue/src/components/UserPage.vue
<template>
  <div class="formcontainer">
        <form name="createUserForm">
          <h1>Dina uppgifter</h1>
          <label for="username">Användarnamn:</label>
          <input
            type="text"
            name="username"
            id="username"
            :value="user.username"
           
            placeholder="användarnamn"
          /><br />
          <label for="password">Lösenord:</label>
          <input
            type="text"
            name="password"
            id="password"
            :value="user.password"
            
            placeholder="lösenord"
          /><br />
          <label for="firstname">Förnamn:</label>
          <input
            type="text"
            name="firstname"
            id="firstname"
            :value="user.firstname"
            
            placeholder="förnamn"
          /><br />
          <label for="lastname">Efternamn:</label>
          <input
            type="text"
            name="lastname"
            id="lastname"
            :value="user.lastname"
            
            placeholder="efternamn"
          /><br />
          <label for="gender">Kön:</label>
          <select id="gender" name="gender" :value="user.gender" >
              <option >{{user.gender}}</option>
          </select>
          <br />
          
        </form>
        <br />
        <router-link to="/" >
          <button @click="$store.commit('logOut')">Logga ut</button>
        </router-link>
    </div>
</template>

<script>
import { mapGetters } from 'vuex'
export default {
  computed: {
    ...mapGetters({user: 'getUser'})
  },
}
</script>

<style>

</style>

// web-display-react/src/UserPage.js
import { render } from "@testing-library/react";
import React, { useState } from "react";
import { Link, Redirect } from 'react-router-dom'

function UserPage(props) {

  const logout = () => {
    localStorage.clear();
    props.setUser({});
    props.setLoggedIn(false)
  };

  return (
    <React.Fragment>
      { 
        props.user[0] ? 
          <div style={{width: '50vw', margin: 'auto'}}>
            <form name="createUserForm">
              <h1>Dina uppgifter</h1>
              <label htmlFor="username">Användarnamn:</label>
              <input
                type="text"
                name="username"
                id="username"
                value={props.user[0].username}
                placeholder="användarnamn"
              /><br />
              <label htmlFor="password">Lösenord:</label>
              <input
                type="text"
                name="password"
                id="password"
                value={props.user[0].password}
                placeholder="lösenord"
              /><br />
              <label htmlFor="firstname">Förnamn:</label>
              <input
                type="text"
                name="firstname"
                id="firstname"
                value={props.user[0].firstname}
                placeholder="förnamn"
              /><br />
              <label htmlFor="lastname">Efternamn:</label>
              <input
                type="text"
                name="lastname"
                id="lastname"
                value={props.user[0].lastname}
                placeholder="efternamn"
              /><br />
              <label htmlFor="gender">Kön:</label>
              <select id="gender" name="gender" value={props.user[0].gender} >
                  <option value="">{props.user[0].gender}</option>
              </select>
              <br />
            </form>
            <br />
            <Link to="/" >
              <button  onClick={logout}>Logga ut</button>
            </Link>
          </div>
        :<div></div>
      }
    </React.Fragment>
  );
}

export default UserPage;
