// web-display-react/src/components/Login.js
import React from "react";
import axios from "axios";
import { Link, Redirect } from "react-router-dom";

function Login(props) {
    const login = (e) => {
        e.preventDefault()
        const user = {username: e.target[0].value, password: e.target[1].value}
        axios
          .get("http://ec2-13-48-85-50.eu-north-1.compute.amazonaws.com:8080/users/find?search="+e.target[0].value)
          .then((res) => {
            if(user.password === res.data[0].password){
              localStorage.setItem('user', JSON.stringify(res.data[0]))
              props.setUser(res.data[0])
              props.setLoggedIn(true)
            }
          })
          .catch(err => console.log(err.response))

      //   axios
      // .post("http://ec2-13-48-204-0.eu-north-1.compute.amazonaws.com:5000/test")
      // .then((res) => console.log(res))
      // .catch(err => {
      //   console.log(err.response)}) 
      }

    return(
      <>
        { props.loggedIn ? <Redirect to='/' /> : null }
        <div className="formcontainer">
          <form id="login_form" onSubmit={(e) => login(e)}>
          <h1 style={{textAlign: 'center'}}>Logga in</h1>
              <label htmlFor="username">Användarnamn:</label>
              <input type="text" name="username" placeholder="användarnamn" />
              <label htmlFor="password">Lösenord:</label>
              <input type="text" name="password" placeholder="lösenord" />
              <br />
              <button>Logga in</button>
          </form>
        </div>
      </>
    )
}

export default Login

// web-display-vue/src/components/Login.vue
<template>
    <br />
    <h1 >Välkommen att logga in</h1>
    <br />
    <div class="formcontainer">
        <form @submit.prevent="logIn">
            <label htmlFor="username">Användarnamn:</label>
            <input type="text" name="username" placeholder="name" />
            <label htmlFor="password">Lösenord:</label>
            <input type="text" name="password" placeholder="pass" />
            <button>Logga in</button>
        </form>
    </div>
</template>

<script>
import axios from 'axios'
import { mapMutations } from 'vuex'

export default {
    name: "Login",
    data() {
        return {
            
        }
    },
    methods: {
        ...mapMutations({setuser: 'setUser', login: 'logIn'}),
        logIn(e){
            //e.preventDefault()
            // console.log('what')
            // this.$store.commit('setUser', {username: 'Tre'})
            // this.$store.commit('logIn')
           
            axios
            .get("http://ec2-13-48-204-0.eu-north-1.compute.amazonaws.com:8080/users/find?search="+e.target[0].value)
            .then((res) => {
                console.log(res.data)
                //this.$store.commit('setUser', res.data[0])
                 //this.$store.commit('logIn')
                 localStorage.setItem('user', JSON.stringify(res.data))
                 this.setuser(res.data[0])
                 this.login()
                })
            .catch(err => console.log(err.response))
        }
    },
}
</script>

<style scoped>
    .formcontainer {
        width: 30vw;
    }
</style>
