// web-display-react/src/Welcome.js
import React from 'react'


function Welcome(props){
    const logout = () => {
        localStorage.clear();
        props.setUser({});
        props.setLoggedIn(false)
      };

    return(
        <React.Fragment>
            <h1>Välkommen {props.user[0].username}</h1>
            <button  onClick={logout}>Logga ut</button>
        </React.Fragment>
    )
}

export default Welcome

// web-display-vue/src/components/Welcome.vue
<template>
  <div>
      <br />
      <h1 >Välkommen {{$store.state.user.username}} </h1>
      <router-link to="/" tag="button" @click="() =>  {$store.commit('logOut');$router.push('/');}">Logga ut</router-link>
      </div>
</template>

<script>


export default {
    name: 'Welcome',
    components: {
        
        
    },

}
</script>

<style>

</style>
